# Generated by Django 4.1.7 on 2023-04-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phonenumber',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
