# Generated by Django 4.1.7 on 2023-04-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_student_phonenumber_alter_student_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
